### PR TITLE
Hud

### PR DESCRIPTION
**Pull request by Faffie**
Add spooky overlay. Restore formatting.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
I think the formatting was already correct? The tabs look very big now

**Comment by Faffie** [comment]
Hm, you're right. I'm sorry, I used the default in Eclipse, instead of whatever Checkstyle wants (even though I disagree). I'm suggesting we use Java convention and apply it to our Checkstyle rules.

**Comment by Faffie** [comment]
I restored the formatting again, also included a checkstyle config in both folders. Also updated gitignore and travis configs.

**Comment by irenevanderblij** [comment]
The formatting still looks the same (large tabs) in the files changed... Is that correct?

**Comment by Faffie** [comment]
Yes, indentation is now set to two spaces according to our checkstyle rules. Even though I personally don't like this, it's what Harvey used initially.

**Pull request merged**
