### PR TITLE
Add various sound effects

### PR DESCRIPTION
**Pull request by Faffie**
Added various sounds. Interacting with certain objects will play sound effects. Starting and completing a minigame will play a sound as well.
Interaction with the door, for example, will play a sound of someone trying to open a locked door. 

Set a longer time window for the spookyscreen overlay, also set it to display 400ms. By popular demand. ;)

### CODE REVIEW

**Comment by irenevanderblij** [comment]
The sounds are fine. We'll need more of those, though. As you didn't really add any functionality, this doesn't really need a pull request does it?

"Set a longer time window for the spookyscreen overlay, also set it to display 400ms. By popular demand. "
Wait what?

**Comment by irenevanderblij** [comment]
I think the popular demand was that the spooky screen would not be shown at all ;) ;).
It is an improvement that it is shown less and shorter. However, I do really think that showing it once is more than enough (this is a compromise since we do not want it at al!!!!!)

**Comment by Faffie** [comment]
Don't you dare touch my spookyscreen!

**Comment by irenevanderblij** [comment]
You know what would be a great idea?  Only show the spooky screen if the name entered matches "Jochem"

**Comment by Faffie** [comment]
Oh that gives me another, even better idea! Thanks!

**Comment by Faffie** [comment]
Just merge this already, it's only assets, not actual functionality. :P

**Comment by irenevanderblij** [comment]
@alanvanrossum @Mayke93 please merge

**Comment by alanvanrossum** [comment]
@irenevanderblij  yes ma'am

**Pull request merged**
