### PR TITLE
Refactor parts of EscapeVR. Added a class for every minigame which no…

### PR DESCRIPTION
**Pull request by irenevanderblij**
…w handles the start and stop actions instead of EscapeVR.

### CODE REVIEW

**Comment by Mayke93** [comment]
good refactor, some checkstyle has been fixed as well

**Comment by alanvanrossum** [comment]
Looks a lot more clear now, although we will have to add an entire classfile here for each minigame we develop in KroketApp

**Comment by Mayke93** [comment]
I do think it is neater though, because the code for the minigames was all over the place

**Comment by Faffie** [comment]
My suggestions is to use String.format for the messages it's sending and perhaps move this to the Protocol class.

**Comment by alanvanrossum** [comment]
right now there is a lot of duplicate code though, most minigame classes are the same except for the start and stop methods

**Comment by alanvanrossum** [comment]
Also, the picturecodeminigame doesn't log or add text to the hud, while the others do?

**Comment by irenevanderblij** [comment]
Oh, huh, you are right Alan. I had already put that in there, but apparently I deleted it... Thanks for pointing that out. I changed it.

**Comment by alanvanrossum** [comment]
alright

**Comment by irenevanderblij** [comment]
Can someone merge?

**Comment by irenevanderblij** [comment]
Pls?

**Comment by Faffie** [comment]
Yessir.

**Pull request merged**
