### PR TITLE
Add simple login dialog to Launcher (JavaFX)

### PR DESCRIPTION
**Pull request by Faffie**
Added a very simple login dialog window to prompt the user for name and remote host.

This uses JavaFX. Java8 was a requirement for this application, so using JavaFX shouldn't be a problem. I considered using the internal dialogs but those have only been available since 8u40. 

The name can be left blank: it'll use VR-USER by default. 
The remote host cannot be left blank. Perhaps we could make it use 'localhost' otherwise?

Other than checking for an empty field, there is no input sanitation/validation in place. The host field can be any string, since I also want it to process hostnames (not just IP addresses).

Please review.

### CODE REVIEW

**Comment by alanvanrossum** [comment]
If it works like just like in the app, this seems good.
I agree a 'blank' remote host should use localhost as default.

**Comment by Faffie** [comment]
Done. Both fields can now be left blank. Will use default entries.

**Comment by irenevanderblij** [comment]
Works fine.

Just one question. Wouldn't it be more intuitive to have the game connect to the server in this new window? And that if the connection succeeds the game really starts and you go to the lobby screen? In that way you could still enter a different IP address if the connection fails (like in the app).

**Comment by irenevanderblij** [comment]
(Also if I click the X button on the top right, the game still starts which is also not intuitive)

**Comment by Faffie** [comment]
Oh, I may have misunderstood your question before. I vaguely remember you asking about rendering the actual game in the same window. I also remember you asking about connecting beforehand. 

I think the latter should be fairly easy, even though it's something I don't really want to have. We can discuss this again during the next meeting.

**Comment by Faffie** [comment]
As for the default window close event: this now terminates the entire application. When I was making/testing the new window I realised pressing the "X-button" would cause unexpected behaviour: the behaviour you mentioned. I spent a few seconds trying to figure out how to catch the event, but as I was in a hurry I couldn't be bothered.
Fixed in another PR.

**Pull request merged**
