### PR TITLE
Begin refactoring VR client

### PR DESCRIPTION
**Pull request by Faffie**
I began refactoring the VR client. I already merged my other changes into this branch. Please review and merge.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
Still the formatting which I question since you merged that from the other branch into this one. The other changes look good.

**Comment by Faffie** [comment]
I agree, but those changes were from before I started refactoring the server and didn't comply with our checkstyle rules. I updated them now.

**Comment by Faffie** [comment]
I don't agree with this formatting to begin with though, I would prefer to change the CS rules to use the Eclipse default. We should discuss this.

**Comment by irenevanderblij** [comment]
Formatting looks fine now. We can discuss this tomorrow during the meeting. This branch still has conflict, which I recommend you first resolve by merging development into this branch

**Comment by Faffie** [comment]
Conflicts were caused due to other branches, I'll resolve those now.

**Comment by Faffie** [comment]
Removed EscapeServer (migrating to different repository).

**Pull request merged**
