### PR TITLE
handle the bonustime message, increase the timer

### PR DESCRIPTION
**Pull request by irenevanderblij**
handle the bonustime message, increase the timer

### CODE REVIEW

**Comment by Faffie** [comment]
I'm fine with this.

**Comment by Faffie** [comment]
I already merged the server-side part of this. Wouldn't make much sense to not merge this one. Everyone else agree with this PR?

**Comment by Faffie** [comment]
Clicked the wrong button. :( Sorry. Reopened.

**Comment by Mayke93** [comment]
It works, so I'll merge it. Code looks good and commented.

**Pull request merged**
