### PR TITLE
Restore original intro 

### PR DESCRIPTION
**Pull request by Faffie**
This PR restores the intro. The intro will be shown after the lobby and can be skipped using the interaction button.
As a minor change, I set the camera's height to 2. 

Each overlay lasts 5 seconds.

### CODE REVIEW

**Comment by Faffie** [comment]
Restored the origin GameWon screen too.

**Comment by irenevanderblij** [comment]
Nice that the intro is restored, and now skippable! We do still need to change the text for the story to become clearer. We also need an intro for the app still.

**Comment by Mayke93** [comment]
if the text is changed, this can be merged

**Comment by Faffie** [comment]
Don't you mean "when"?

**Comment by Faffie** [comment]
Alan will update the overlays.

**Comment by alanvanrossum** [comment]
Alright the new intro should be all up and running and looking more beautiful than ever. If one more member can test this and see if they like it, we can start resolving merge conflicts and get this to merge.

**Comment by harveyvanveltom** [comment]
Nice job on the new overlays. However I was thinking if it would be a good idea to add an overlay that describes the controls of the game. AKA use left stick to move and A to interact. Because  until now we made the assumption that the player was able to figure the controls out however i'm afraid some players are gonna end up confused because they cannot figure out how to interact with the scene.

**Comment by irenevanderblij** [comment]
I definitely agree with what Harvey says!

The overlays look good

**Comment by alanvanrossum** [comment]
nice point harvey, i'll make sure it gets added

**Comment by alanvanrossum** [comment]
Added an insructional slide which shows the controls, the image can be found at https://github.com/alanvanrossum/kroket/blob/intro/EscapeVR/assets/Interface/Overlay/controls.png

Feedback is always welcome, an easy change now can make a world of a difference when a lot of players will play this game.

**Comment by irenevanderblij** [comment]
looks great!

**Comment by Faffie** [comment]
I shared my feedback on the instruction panel elsewhere.

**Comment by irenevanderblij** [comment]
The intro does cause problems with the timer, since the timer on the host is started before the intro starts playing (instead of after)

**Comment by Faffie** [comment]
As expected, I didn't think that would matter but... perhaps letting the timer run here exclusively might be a better approach, as you mentioned earlier.

**Comment by harveyvanveltom** [comment]
looks good.

**Pull request merged**
