### PR TITLE
Development

### PR DESCRIPTION
**Pull request by irenevanderblij**
Pull branch development into master for pre-release 6.

### CODE REVIEW

**Comment by alanvanrossum** [comment]
I have already reviewed all these commits, as they were pull-requested to development. If someone else agrees he or she can merge this. (providing travis passes)

**Comment by Mayke93** [comment]
Everything is as expected.

**Comment by harveyvanveltom** [comment]
You forgot to add a discription

**Comment by irenevanderblij** [comment]
I am so terribly sorry. I will definitely add this next time.

**Comment by alanvanrossum** [comment]
add it now

**Comment by harveyvanveltom** [comment]
you better or else

**Comment by irenevanderblij** [comment]
Okay okay

**Comment by Mayke93** [comment]
No fighting

**Comment by irenevanderblij** [comment]
All checks have passed, please merge

**Comment by Faffie** [comment]
I know a PR like this is rather silly, but can we refrain from making goofy remarks here and at least pretend to be serious, please?

**Pull request merged**
