### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by Faffie**
Applied several bugfixes for Oculus users. Overlays weren't display properly. Gamestates weren't saved properly.

### CODE REVIEW

**Comment by Mayke93** [comment]
Why have you pushed models on a bugfix branch?
The bugfix works, and overlays are displayed correctly now.

**Comment by Faffie** [comment]
The models were in the decoration branch and this branch was in sync with decoration.

**Comment by irenevanderblij** [comment]
What does it fix exactly?

**Comment by Faffie** [comment]
Overlays were displayed multiple times, making alpha channel images appear as opaque. 
Also, the new game state wasn't being saved, making it use the old state, I'm not sure when this bug was introduced. Because the timing was "just right", it remained unnoticed until I started fiddling with the alpha test.

**Comment by alanvanrossum** [comment]
Shouldn't the alpha test be removed?!?!

**Comment by Faffie** [comment]
I want to keep it on our repository to test alpha channel images with the Oculus. It's not used in the code anyway.

**Comment by alanvanrossum** [comment]
Fine

**Comment by Faffie** [comment]
Thanks. Geeze that was painful, you people are hardcore code reviewers.

**Pull request merged**
