### PR TITLE
Refactor controls

### PR DESCRIPTION
**Pull request by Faffie**
I refactored the controls/event handling, also dealt with collision somewhat differently.  Registering new triggers/controls and firing new events should be easier. 

Please review/pull/merge.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
The code in the pull request starts the game in debug mode, is this on purpose?
Nice work on the handlers; the splitting of the code into the separate handlers makes it clearer.

**Comment by Faffie** [comment]
"The code in the pull request starts the game in debug mode, is this on purpose?"

Not necessarily, but we mostly skip the lobby during development anyway, we did as well during previous iterations (and restored it before the end of each iteration). I figured this wouldn't matter much. 

Thank you. I think it should be somewhat easier to expand and test as well, primarily for the EventHandling.

**Comment by irenevanderblij** [comment]
I agree that it is easier to develop in debug mode. We just should not forget to change this in the release.

**Comment by Faffie** [comment]
I keep an eye on these things, but if it's bothersome...
Perhaps we could make a local environment variable/local settings file, or maintain a policy that any code on the development branch is always in "normal" mode. It's just something to keep an eye on before release, just like the pom files and a few other things. I do agree this may seem risky.

**Comment by harveyvanveltom** [comment]
Looks good. The code looks a lot cleaner now and a lot easier to test. can be safely merged

**Pull request merged**
