### PR TITLE
Javadoc, javadoc, and... more javadoc!

### PR DESCRIPTION
**Pull request by irenevanderblij**
The whole EscapeVR is now javadoc'ed, yay!

### CODE REVIEW

**Comment by Faffie** [comment]
https://www.youtube.com/watch?v=9UZWfMgjqAs

**Comment by Faffie** [comment]
Javadoctor Irene.

**Comment by Faffie** [comment]
Yeah uhm, nice?

**Comment by Mayke93** [comment]
goooood :dancers:

**Pull request merged**
