### PR TITLE
Minor updates to VR client

### PR DESCRIPTION
**Pull request by Faffie**
Minor updates to VR client.
Locked player on horizontal axis during PlayingState (y is kept to 0).
Observer is spawned outside of room after GameWon and can fly. Updated horizon.
Renamed 'assets/Interface/overlay' to 'assets/Interface/Overlay' to get rid of duplicate directory on repository.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
Nice job on locking the Y-axis. Works well!

The 360 view when the game is won also looks nice. However, you can still see the room flying in the starry sky, this feels kind of odd to me. Can't we just destroy the room? Also it would be nice if some text is shown in this view that lets you know that you won the game.

**Comment by Faffie** [comment]
Yeah, an overlay (shown for a few seconds) is what I had in mind. I really just wanted to dump the player in front of the door for comic effect. The superman effect with the Oculus is pretty cool so I kind of want to keep that. Maybe always move the player forward to keep a flying effect?

**Comment by Faffie** [comment]
Woops. Closed by accident.

**Comment by irenevanderblij** [comment]
I am not sure what you mean? Is the 'superman effect' gone when the room is deleted?

**Comment by Faffie** [comment]
No I don't mind about destroying the room, I just think keeping it there and having the player see the room could be funny, "oh.. I.. got kicked out, okay!?".

**Comment by Faffie** [comment]
Please review again. :)

**Comment by Faffie** [comment]
The fixed y-coordinate should probably be a setting, or should consider the spawnPosition.

**Comment by Mayke93** [comment]
I see the player cannot not fly any more when moving forwards when looking up, this is good. However I do think we should set the height further from the floor, because the height of the camera is currently about the same as the desk.

**Comment by Faffie** [comment]
I agree, but that's why it should consider the spawn position or be a setting. The value isn't relevant.

**Comment by irenevanderblij** [comment]
Since we agree on the changes in this PR, I will merge

**Pull request merged**
