### PR TITLE
Refactor protocol & state handling

### PR DESCRIPTION
**Pull request by Faffie**
Refactored protocol. Also updated the music and overlay for the lobby screen. 

Updated version number in pom,

### CODE REVIEW

**Comment by irenevanderblij** [comment]
When I interact with an object that should trigger a minigame, I always get the message on the screen that the minigame is started, even though it is for example already running on the mobile devices.

**Comment by irenevanderblij** [comment]
Also, minigame B now is ended on both mobile devices when only one player has finished it. This is not what is meant to happen.

**Comment by irenevanderblij** [comment]
The buttons for minigame C have weird colors (they are all blueish), not only on my pc but also on Mayke's.

**Comment by Mayke93** [comment]
You can also do minigame a and b, and then a again. 
Minigame B is also broken, both smartphone players need to complete this, and this is not the case in this refactor. Minigame c does not work anymore.

**Comment by Mayke93** [comment]
Also, the vr client still seems to send an INITM message with doneC. The host seems to receive this multiple times, or at least it gives the messages 
"[11:12:39]: ERROR ClientInstance: Invalid command : INITM
[11:12:39]: INFO ClientInstance: Input received: INITM[doneC]" on sort of loop.

Minigame C was not even finished at the time these messages were appearently sent. This did not happen before.

**Comment by Faffie** [comment]
They were blue because I had the ambient light set to blue (instead of white). It annoys me how this couldn't be noticed on other objects. 

I know I broke a few things before, but... come on, with such a huge pile of hacks, don't you dare blame me. Yeah, it worked, but did you ever read your own code?

As for the protocol...
"INIT", meaning "initialize" (begin), and then having "done" (the opposite of beginning!) and having a parameter appended to another parameter ("done" and "C"), encapsulated as a single parameter?????
Who thought expanding this mess was a good idea to begin with? 

I don't know how you sleep at night, pestering me with this. You barbarians, you!

**Comment by irenevanderblij** [comment]
Thanks for updating the refactor. The buttons have the color again! Also, everything seems to work now :) 

I know you said to ignore what happens after minigame C, but I do want to mention that it would be better if no object triggers a minigame. Right now, every object triggers a message with BEGIN[D] if I am not mistaken, and for the app player minigame C starts again (when I interacted with buttons again). 

After minigame B has been merged, all conflicts can be resolved and this can be merged aswell!

**Comment by Faffie** [comment]
Tested thoroughly. Got rid of some dodgy code. I guess this is ready to be merged.

**Comment by harveyvanveltom** [comment]
Alright looks like this pull request is working as intended. nice job the refactor removes a lot of existing smelly code which was necessary.

**Pull request merged**
