### PR TITLE
new desk

### PR DESCRIPTION
**Pull request by Mayke93**
A new desk is added, and some checkstyle is fixed.

Can people please test so we know this will not crash the game for anyone. Also it needs to be tested if this desk allows the player to interact with it easily. We'll also need to run a test to know for sure the interaction still works properly.

### CODE REVIEW

**Comment by Faffie** [comment]
Aw, I liked the desk in the corner :( I would've liked a chopped-up version better, but fine. The wall collision is still disabled amirite?

**Comment by Mayke93** [comment]
Oops, you are right about the wall collision, I'll change that. The other desk was nice, but the interaction was very user unfriendly, and it crashed on one machine.

**Comment by Faffie** [comment]
Oh, right. The assets we're using are huge though so that's no surprise. Well I'm fine with this object.

**Comment by irenevanderblij** [comment]
The new desk looks good and is way better to interact with than the previous one! I agree with this being merged

**Pull request merged**
